trigger:
- main

pool:
  name: LocalPool   # Your self-hosted pool name
  demands:
    - agent.name -equals MyLocalAgent

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'my-app/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: '/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install'
    mavenVersionOption: 'Default'

- task: PublishPipelineArtifact@1
  displayName: 'Publish build artifact'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/my-app/target'
    artifact: 'maven-build'
    publishLocation: 'pipeline'